version: 0.2

phases:
    install:
        runtime-versions:
            nodejs: 10
        commands:
            - echo Installing source NPM dependencies...
            - npm install
            - npm install -g @angular/cli
    build:
        commands:
            - echo Build started on `date`
            - ng build --prod
    post_build:
        commands:
            - aws s3 rm s3://${S3_BUCKET} --recursive
            - echo S3 bucket is cleared.
            - aws s3 cp dist/ch-web s3://www.colby-hill.com --recursive
            - echo Build completed on `date`
            - echo Build completed on `date`
        
artifacts:
    files:
        - '**/*'
    base-directory: 'dist*'
    discard-paths: yes